service: challenge-orchestrator
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  environment:
    CUSTOMERS_API_URL: ${env:CUSTOMERS_API_URL}
    ORDERS_API_URL: ${env:ORDERS_API_URL}
    SERVICE_TOKEN: ${env:SERVICE_TOKEN}
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  serverless-offline:
   noPrependStageInUrl: true
   httpPort: 3000
   lambdaPort: 3004

functions:
  createAndConfirmOrder:
    handler: src/handler.createAndConfirmOrder
    events:
      - http:
          path: orchestrator/create-and-confirm-order
          method: post
          cors: true